import { useSearchParams } from 'react-router-dom';

import { PageHeading } from '@/components/layout/PageHeading';
import {
  Button,
  EmptyState,
  ErrorState,
  FormField,
  Input,
  Select,
  Skeleton,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeadCell,
  TableRow,
} from '@/components/ui';
import { MESSAGES } from '@/constants/messages';
import { ROLE } from '@/constants/roles';
import { useSitesQuery } from '@/features/config';
import { useAuth } from '@/hooks/useAuth';
import { useToast } from '@/hooks/useToast';
import { usePageTitle } from '@/hooks/usePageTitle';
import { formatTimestamp } from '@/lib/format/formatTimestamp';
import { cn } from '@/lib/utils/cn';
import { downloadBlob } from '@/lib/utils/downloadBlob';

import { useExportReport } from '../api/useExportReport';
import { useReportSummary } from '../api/useReportSummary';
import { GROUP_BY_OPTIONS, GROUP_LABEL, groupName } from '../types';
import { DecisionMixBar } from './DecisionMixBar';
import { VerifiedBarChart } from './VerifiedBarChart';

import type { ChangeEvent, ReactNode } from 'react';
import type { ReportSummary } from '@/lib/api/types';
import type { GroupBy, ReportParams } from '../types';

const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
const DEFAULT_PERIOD_DAYS = 7;

// CS-G-13 — URL params are untrusted external input.
const parseDateParam = (value: string | null): string | null =>
  value !== null && DATE_PATTERN.test(value) ? value : null;

const parseGroupBy = (value: string | null): GroupBy =>
  GROUP_BY_OPTIONS.find((option) => option === value) ?? 'zone';

const isoDate = (date: Date): string => date.toISOString().slice(0, 10);

const defaultFrom = (): string => {
  const date = new Date();
  date.setUTCDate(date.getUTCDate() - DEFAULT_PERIOD_DAYS);
  return isoDate(date);
};

type StatTone = 'neutral' | 'danger' | 'warn';

// CS-Y-05 — tone resolves through a closed lookup. Danger / warn tiles are
// status-tinted because they ARE statuses (BR-R-03, coverage gaps); the
// categorical chart-1..5 palette is reserved for series and is never used
// as a status (CS-Y-11).
const TILE_TONE_CLASS: Record<StatTone, string> = {
  neutral: 'border-border bg-surface-1',
  danger: 'border-danger bg-danger-subtle',
  warn: 'border-warn bg-warn-subtle',
};

const StatPanel = ({
  label,
  value,
  note,
  tone = 'neutral',
}: {
  label: string;
  value: ReactNode;
  note?: string | undefined;
  tone?: StatTone;
}) => (
  <div className={cn('rounded-card border p-4 shadow-ambient', TILE_TONE_CLASS[tone])}>
    <p className="text-sm text-fg-muted">{label}</p>
    <p className="mt-1 text-3xl font-semibold tabular-nums text-fg">{value}</p>
    {note !== undefined ? <p className="mt-1 text-xs text-fg-muted">{note}</p> : null}
  </div>
);

const SummaryView = ({ summary, groupBy }: { summary: ReportSummary; groupBy: GroupBy }) => {
  const totalVerified = summary.groups.reduce((sum, group) => sum + group.verified_count, 0);
  const basisLabel =
    summary.basis === 'verified_events_only' ? 'verified events only' : summary.basis;

  return (
    <div className="space-y-4">
      {/* BR-R-02 — a report states its period, generating user and basis. */}
      <p className="text-sm tabular-nums text-fg-muted">
        Basis: {basisLabel} · Generated by {summary.generated_by.full_name} at{' '}
        {formatTimestamp(summary.generated_at)} · Period {summary.period.from} →{' '}
        {summary.period.to}
      </p>

      <div className="grid gap-4 sm:grid-cols-3">
        <StatPanel label="Verified records" value={totalVerified} />
        {/* BR-R-03 / CS-B-09 — the rejection count is visible, never hidden. */}
        <StatPanel
          tone="danger"
          label="Rejected candidates"
          value={summary.decision_counts?.rejected ?? '—'}
          note="Rejections are retained and visible (BR-007)"
        />
        {/* ARCHITECTURE §6.5 — a zero-event report must be readable against
            the coverage gaps for the same window. */}
        <StatPanel
          tone="warn"
          label="Coverage gaps"
          value={`${summary.coverage_gaps_minutes} min`}
          note="gaps in analysis during this period"
        />
      </div>

      {summary.decision_counts !== undefined ? (
        <section
          aria-label="Decision mix"
          className="rounded-card border border-border bg-surface-1 p-4 shadow-ambient"
        >
          <h3 className="text-sm font-semibold text-fg">Decision mix</h3>
          <p className="mt-0.5 text-xs text-fg-muted">
            Every decision of the period — accepted, corrected and rejected are all visible
            (BR-R-03).
          </p>
          <div className="mt-3">
            <DecisionMixBar counts={summary.decision_counts} />
          </div>
        </section>
      ) : null}

      {summary.groups.length === 0 ? (
        <EmptyState
          title="No verified records in this period"
          detail="Read this together with the coverage gaps above: zero events may mean zero exceptions or zero watching."
        />
      ) : (
        <div className="grid gap-4 xl:grid-cols-5">
          <section
            aria-label={`Verified records by ${GROUP_LABEL[groupBy].toLowerCase()}`}
            className="rounded-card border border-border bg-surface-1 p-4 shadow-ambient xl:col-span-3"
          >
            <h3 className="text-sm font-semibold text-fg">
              Verified records by {GROUP_LABEL[groupBy].toLowerCase()}
            </h3>
            <div className="mt-3">
              <VerifiedBarChart groups={summary.groups} groupBy={groupBy} />
            </div>
          </section>
          <Table className="xl:col-span-2 self-start">
            <TableHead>
              <TableHeadCell>{GROUP_LABEL[groupBy]}</TableHeadCell>
              <TableHeadCell className="text-right">Verified records</TableHeadCell>
            </TableHead>
            <TableBody>
              {summary.groups.map((group) => (
                <TableRow
                  key={`${group.zone ?? ''}|${group.rule ?? ''}|${group.day ?? ''}|${group.shift ?? ''}`}
                >
                  <TableCell>{groupName(group)}</TableCell>
                  <TableCell className="text-right tabular-nums">{group.verified_count}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      )}
    </div>
  );
};

export const ReportsPage = () => {
  usePageTitle('Reports');
  const { principal } = useAuth();
  const [searchParams, setSearchParams] = useSearchParams();
  const isSiteAdmin = principal !== null && principal.roles.includes(ROLE.SITE_ADMIN);
  const sitesQuery = useSitesQuery(isSiteAdmin);

  // CS-RT-03 — the period, grouping and site selection live in the URL.
  const from = parseDateParam(searchParams.get('from')) ?? defaultFrom();
  const to = parseDateParam(searchParams.get('to')) ?? isoDate(new Date());
  const groupBy = parseGroupBy(searchParams.get('group_by'));
  const siteId = searchParams.get('site_id') ?? sitesQuery.data?.[0]?.id ?? null;

  const params: ReportParams = {
    from: `${from}T00:00:00Z`,
    to: `${to}T23:59:59Z`,
    groupBy,
    siteId,
  };
  const summaryQuery = useReportSummary(params);
  const exportReport = useExportReport();
  const { showToast } = useToast();

  const updateParam = (key: string, value: string): void => {
    setSearchParams(
      (current) => {
        const next = new URLSearchParams(current);
        next.set(key, value);
        return next;
      },
      { replace: true },
    );
  };

  const handleFromChange = (event: ChangeEvent<HTMLInputElement>): void => {
    updateParam('from', event.target.value);
  };
  const handleToChange = (event: ChangeEvent<HTMLInputElement>): void => {
    updateParam('to', event.target.value);
  };
  const handleGroupByChange = (event: ChangeEvent<HTMLSelectElement>): void => {
    updateParam('group_by', event.target.value);
  };
  const handleSiteChange = (event: ChangeEvent<HTMLSelectElement>): void => {
    updateParam('site_id', event.target.value);
  };
  const handleExport = (): void => {
    exportReport.mutate(params, {
      onSuccess: (blob) => {
        downloadBlob(blob, `guardian-lens-report-${from}-to-${to}.csv`);
        // BR-R-02 — the outcome names the provenance the file carries.
        showToast({ tone: 'success', message: MESSAGES.reports.exportReady });
      },
      onError: () => {
        showToast({ tone: 'failure', message: MESSAGES.reports.exportFailed });
      },
    });
  };

  let content: ReactNode;
  if (summaryQuery.isPending) {
    // CS-Y-13 — skeleton tiles in the resolved layout; no shift on load.
    content = (
      <div aria-label="Loading report" className="space-y-4">
        <p className="sr-only">Loading report…</p>
        <Skeleton className="h-4 w-2/3" />
        <div className="grid gap-4 sm:grid-cols-3">
          <Skeleton className="h-28 rounded-card" />
          <Skeleton className="h-28 rounded-card" />
          <Skeleton className="h-28 rounded-card" />
        </div>
        <Skeleton className="h-48 w-full rounded-card" />
      </div>
    );
  } else if (summaryQuery.isError || summaryQuery.data === undefined) {
    content = (
      <ErrorState
        title="The report could not be loaded."
        onRetry={() => void summaryQuery.refetch()}
      />
    );
  } else {
    content = <SummaryView summary={summaryQuery.data} groupBy={groupBy} />;
  }

  return (
    <section aria-label="Reports" className="space-y-4">
      <div>
        <PageHeading>Reports</PageHeading>
        <p className="mt-1 text-sm text-fg-muted">
          Verified records only — nothing unreviewed is counted here (BR-004).
        </p>
      </div>
      {/* Filters in one row above the analysis, URL-backed (CS-RT-03). */}
      <div className="flex flex-wrap items-end gap-3 rounded-card border border-border bg-surface-1 p-4 shadow-ambient">
        <FormField label="From" className="w-40">
          <Input type="date" value={from} onChange={handleFromChange} />
        </FormField>
        <FormField label="To" className="w-40">
          <Input type="date" value={to} onChange={handleToChange} />
        </FormField>
        <FormField label="Group by" className="w-36">
          <Select value={groupBy} onChange={handleGroupByChange}>
            {GROUP_BY_OPTIONS.map((option) => (
              <option key={option} value={option}>
                {GROUP_LABEL[option]}
              </option>
            ))}
          </Select>
        </FormField>
        {isSiteAdmin ? (
          <FormField label="Site" className="w-44">
            <Select value={siteId ?? ''} onChange={handleSiteChange}>
              {(sitesQuery.data ?? []).map((site) => (
                <option key={site.id} value={site.id}>
                  {site.name}
                </option>
              ))}
            </Select>
          </FormField>
        ) : null}
        <div className="ml-auto">
          <Button variant="secondary" onClick={handleExport} isLoading={exportReport.isPending}>
            Export CSV
          </Button>
        </div>
      </div>
      {content}
    </section>
  );
};
