#!/usr/bin/env bash
# One command to run the whole stack: database, control plane API, review UI.
#
#   make run        (or: bash scripts/run_dev.sh)
#
# What it does, in order — each step is the production code path:
#   1. postgres up (docker compose) and healthy
#   2. control schema migrated
#   3. demo tenant provisioned through guardian_lens.db.provisioning
#      (create -> migrate -> identity -> seed -> FF-11 attest -> active)
#   4. first admin bootstrapped (idempotent)
#   5. API on :8000, review UI on :5173 — Ctrl-C stops both
#
# The edge agent is NOT started here: it belongs on a site, not in the
# control plane's process group. Run it against this stack with:
#   make edge-demo
set -euo pipefail
cd "$(dirname "$0")/.."

# .env is the single source of truth. docker compose reads it automatically
# for ${POSTGRES_*} substitution, so this script MUST read the same file —
# otherwise the database comes up on one port with one set of credentials
# and everything else connects somewhere else.
if [ -f .env ]; then set -a; . ./.env; set +a; fi

VENV=.venv/bin
TENANT="${GL_DEMO_TENANT:-pilot}"
# The review-UI port. Overridable (GL_WEB_PORT in .env) for machines where
# another project's dev server owns 5173; keep GL_CORS_ORIGINS in step.
WEB_PORT="${GL_WEB_PORT:-5173}"
ADMIN_EMAIL="${GL_DEMO_ADMIN_EMAIL:-admin@guardianlens.local}"
PG_USER="${POSTGRES_USER:-guardian}"
PG_PASS="${POSTGRES_PASSWORD:-guardian}"
PG_PORT="${POSTGRES_PORT:-5432}"
PG_HOST="${POSTGRES_HOST:-localhost}"
export GL_BOOTSTRAP_PASSWORD="${GL_BOOTSTRAP_PASSWORD:-guardian-dev-1}"
export GL_JWT_SECRET="${GL_JWT_SECRET:-dev-only-secret-change-me-32bytes!}"
# Camera-credential sealing key (AES-256-GCM, TRD 12.4). Generated ONCE and
# persisted to .env: a key that changes between runs would orphan every
# credential sealed under the previous one.
if [ -z "${GL_CAMERA_KEY:-}" ]; then
  GL_CAMERA_KEY=$($VENV/python -c "import secrets; print(secrets.token_hex(32))")
  printf '\n# Camera credential sealing key — generated by make run, never commit\nGL_CAMERA_KEY=%s\nGL_CAMERA_KEY_ID=dev-key-1\n' "$GL_CAMERA_KEY" >> .env
  echo "    generated GL_CAMERA_KEY and persisted it to .env"
fi
export GL_CAMERA_KEY GL_CAMERA_KEY_ID="${GL_CAMERA_KEY_ID:-dev-key-1}"
export GL_CONTROL_DB_URL="${GL_CONTROL_DB_URL:-postgresql+psycopg://${PG_USER}:${PG_PASS}@${PG_HOST}:${PG_PORT}/${GL_CONTROL_DB_NAME:-gl_control}}"
export GL_TENANT_DB_URL="${GL_TENANT_DB_URL:-postgresql+psycopg://${PG_USER}:${PG_PASS}@${PG_HOST}:${PG_PORT}/gl_tenant_${TENANT}}"
echo "    control db: ${GL_CONTROL_DB_URL%%:*}://${PG_USER}@${PG_HOST}:${PG_PORT}"

echo "==> [1/5] postgres"
# Three cases, probed in order:
#   a. a server is already reachable at POSTGRES_HOST:POSTGRES_PORT with the
#      .env credentials → use it, start nothing (a system PostgreSQL is a
#      perfectly good dev database; docker is the fallback, not a demand)
#   b. the port is occupied but the credentials are refused → stop with a
#      clear message rather than fighting over the port
#   c. nothing is listening → start the docker compose database
probe() {
  $VENV/python - <<PROBE
import sys, psycopg
try:
    psycopg.connect(
        "postgresql://${PG_USER}:${PG_PASS}@${PG_HOST}:${PG_PORT}/postgres",
        connect_timeout=3,
    ).close()
    sys.exit(0)
except psycopg.OperationalError as exc:
    text = str(exc)
    sys.exit(2 if ("authentication" in text or "password" in text) else 1)
PROBE
}
set +e; probe; PROBE_RC=$?; set -e
case "$PROBE_RC" in
  0)
    echo "    using existing PostgreSQL at ${PG_HOST}:${PG_PORT} — docker not started"
    ;;
  2)
    echo "    a server is listening on ${PG_HOST}:${PG_PORT} but refused the"
    echo "    credentials in .env — fix POSTGRES_USER/POSTGRES_PASSWORD there."
    exit 1
    ;;
  *)
    docker compose -f docker-compose.dev.yml up -d
    until docker compose -f docker-compose.dev.yml exec -T db pg_isready -q; do sleep 1; done
    # The postgres image applies POSTGRES_USER/PASSWORD only when the volume
    # is FIRST initialised; if .env changed since, reinitialise (dev data
    # only — everything here is regenerated by this script).
    if ! docker compose -f docker-compose.dev.yml exec -T \
          -e PGPASSWORD="${PG_PASS}" db \
          psql -U "${PG_USER}" -d postgres -c "SELECT 1" -q >/dev/null 2>&1; then
      echo "    credentials in .env do not match the existing database volume"
      echo "    reinitialising (docker compose down -v) — dev data only"
      docker compose -f docker-compose.dev.yml down -v
      docker compose -f docker-compose.dev.yml up -d
      until docker compose -f docker-compose.dev.yml exec -T db pg_isready -q; do sleep 1; done
    fi
    ;;
esac

# The control database itself must exist before alembic can connect to it —
# a docker first boot creates it via POSTGRES_DB, an existing server may not
# have it yet.
$VENV/python - <<CREATEDB
import psycopg
from psycopg import sql
name = "${GL_CONTROL_DB_NAME:-gl_control}"
with psycopg.connect(
    "postgresql://${PG_USER}:${PG_PASS}@${PG_HOST}:${PG_PORT}/postgres",
    autocommit=True,
) as conn:
    if conn.execute(
        "SELECT 1 FROM pg_database WHERE datname = %s", (name,)
    ).fetchone() is None:
        conn.execute(sql.SQL("CREATE DATABASE {}").format(sql.Identifier(name)))
        print(f"    created database {name}")
CREATEDB

echo "==> [2/5] control schema"
$VENV/alembic -n control upgrade head >/dev/null

echo "==> [3/5] tenant '${TENANT}'"
$VENV/python - "$TENANT" <<'PY'
import sys
from guardian_lens.db.provisioning import ensure_tenant
slug = sys.argv[1]
# Provision-or-adopt: walks whatever half-state a dev machine holds (bare
# database, missing registry row, dropped database) to attested + active.
ensure_tenant(slug, f"Dev tenant {slug}")
print(f"    '{slug}' attested and active")
PY

echo "==> [4/5] admin ${ADMIN_EMAIL}"
$VENV/python - "$TENANT" "$ADMIN_EMAIL" <<'PY'
import hashlib, os, sys
import psycopg
from guardian_lens.db.urls import psycopg_url
slug, email = sys.argv[1], sys.argv[2]
digest = hashlib.sha256(email.strip().lower().encode()).digest()
with psycopg.connect(psycopg_url(os.environ["GL_CONTROL_DB_URL"])) as conn:
    exists = conn.execute(
        "SELECT 1 FROM user_directory WHERE email_hash = %s", (digest,)
    ).fetchone()
if exists:
    print(f"    {email} already bootstrapped")
else:
    from guardian_lens.api.bootstrap import bootstrap
    bootstrap(slug, email, "Dev Admin",
              site_name="Dev Plant", timezone_name="Asia/Kolkata")
    print(f"    bootstrapped {email} (site 'Dev Plant')")
PY

echo "==> [5/5] API :8000 + web :${WEB_PORT}"
# Always reconcile web dependencies — agents and teammates add packages,
# and a dev server running against stale node_modules fails with confusing
# compile errors. With a matching lockfile this is a ~0.5s no-op.
(cd web && npm install --no-audit --no-fund >/dev/null)

# A previous run's server can survive its parent and keep the port — the
# new server then dies silently into the log while the browser talks to a
# process running week-old code. Clear OUR stale listeners (vite / the
# guardian_lens API only, never an unrelated process) before binding.
free_port() {
  local port="$1" pattern="$2" pid i
  # `|| true`: with pipefail, an empty grep (port free — the NORMAL case)
  # would otherwise fail the assignment and set -e would kill the script.
  pid=$(ss -ltnp 2>/dev/null | grep ":${port} " | grep -oP 'pid=\K[0-9]+' | head -1 || true)
  if [ -n "${pid:-}" ]; then
    if ps -p "$pid" -o args= | grep -qE "$pattern"; then
      echo "    clearing stale dev server on :${port} (pid ${pid})"
      kill "$pid" 2>/dev/null || true
      # A graceful shutdown can outlive a fixed sleep; wait for the port to
      # actually free, then escalate. A guard that "kills" but leaves the
      # port bound produces the silent port-drift it exists to prevent.
      for i in 1 2 3 4 5 6 7 8 9 10; do
        ss -ltn 2>/dev/null | grep -q ":${port} " || return 0
        sleep 0.5
      done
      kill -9 "$pid" 2>/dev/null || true
      sleep 1
    else
      echo "    ERROR: port ${port} is held by a non-dev process (pid ${pid}):"
      ps -p "$pid" -o args= | sed 's/^/      /'
      exit 1
    fi
  fi
}
free_port 8000 "guardian_lens.api"
free_port "$WEB_PORT" "vite.*--port ${WEB_PORT}"

# A training worker has no listening port, so the stale-port guard above
# cannot find it. Stop only workers whose current directory is THIS checkout;
# otherwise repeated make-run cycles would train the same dataset twice.
for pid in $(pgrep -f '[.]venv/bin/python scripts/training_worker.py' || true); do
  if [ "$(readlink -f "/proc/${pid}/cwd" 2>/dev/null || true)" = "$(pwd -P)" ]; then
    echo "    clearing stale training worker (pid ${pid})"
    kill "$pid" 2>/dev/null || true
    for i in 1 2 3 4 5 6; do
      kill -0 "$pid" 2>/dev/null || break
      sleep 0.5
    done
    if kill -0 "$pid" 2>/dev/null; then
      echo "    stale worker is inside a training call; forcing it to stop"
      kill -9 "$pid" 2>/dev/null || true
    fi
  fi
done

cleanup() { kill 0 2>/dev/null || true; }
trap cleanup EXIT INT TERM

mkdir -p var
$VENV/python -m guardian_lens.api &
(cd web && VITE_API_URL="${VITE_API_URL:-http://localhost:8000}" \
  npx vite --port "$WEB_PORT" --strictPort >../var/web-dev.log 2>&1) &
if [ "${GL_TRAINING_ENABLED:-0}" = "1" ]; then
  $VENV/python scripts/training_worker.py >var/training-worker.log 2>&1 &
fi

sleep 2
cat <<BANNER

  Guardian Lens is running.
    Review UI   http://localhost:${WEB_PORT}
    API         http://localhost:8000/api/v1/health
    Login       ${ADMIN_EMAIL} / \$GL_BOOTSTRAP_PASSWORD (default guardian-dev-1)

  Feed it events from a simulated site:   make edge-demo
  Web dev-server log:                     var/web-dev.log
  Training worker:                        ${GL_TRAINING_ENABLED:-0} (var/training-worker.log)
  Stop:                                   Ctrl-C

BANNER
wait
